---
title: "Übung 2"
author: "Valentin Marquart"
date: "`r Sys.Date()`"
output:
  pdf_document:
    keep_tex: yes
    latex_engine: lualatex
  html_document: default
---



1. run io.R
2. import Data and do data wrangeling / clean up in external R.script
3. save cleaned data as RData file `cleandata.RData`
3. analyize and compute data here in RMD-chunks


```{r, echo= FALSE}
# Load your data from an existing project, skip large import scripts and data wrangling
load('cleandata.RData')
plot(gwt$`GW-Temperatur_Nov2009`)

```

```{r}
# Do cool stuff with your imported data
plot(gwt$`GW-Temperatur2010`)
```




\newpage
```{r, echo=TRUE}
n = 100
p = 0.03
x = seq(0,30)
par(mfrow=c(1,3)) # Plot 3 figures, side by side

lambda_003 = n*p
p_x = (lambda_003^(x)/factorial(x))*exp(lambda_003)
plot(p_x, type='b',ylab='Poisson-Wahrscheinlichkeit p_x',main='Poisson-Verteilung \n mit p=0.03')

lambda_001 = n*0.01
p_x = (lambda_001^(x)/factorial(x))*exp(lambda_001)
plot(p_x, type='b',ylab='Poisson-Wahrscheinlichkeit p_x', main='Poisson-Verteilung \n mit p=0.01')

lambda_010 = n*0.1
p_x = (lambda_010^(x)/factorial(x))*exp(lambda_010)
plot(p_x, type='b',ylab='Poisson-Wahrscheinlichkeit p_x',main='Poisson-Verteilung \n mit p=0.10')

```



\newpage
Anmerkungen und Shortcuts
---

\itemize
\item Check Spelling	`F7`
\item Replace and Find	`Command+Shift+J`
\item Compile PDF/HTML with `CMD-SHIFT-K`

